// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBupiz-mn2BaiCwRsDEOwe2GMvR3PLYbbQ',
    appId: '1:890807422379:web:1c62cf38d9c97dcd86d6ee',
    messagingSenderId: '890807422379',
    projectId: 'womensafety-81e08',
    authDomain: 'womensafety-81e08.firebaseapp.com',
    storageBucket: 'womensafety-81e08.firebasestorage.app',
    measurementId: 'G-19M2NLMKZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR-uKZ2oXZQge03T_t7Se4fslN6SrdJzU',
    appId: '1:890807422379:android:a5ad5ecef04df69d86d6ee',
    messagingSenderId: '890807422379',
    projectId: 'womensafety-81e08',
    storageBucket: 'womensafety-81e08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMxnwfPTudvRN8u7T50NhQtyDThgoatoI',
    appId: '1:890807422379:ios:73e74ad7271deaf986d6ee',
    messagingSenderId: '890807422379',
    projectId: 'womensafety-81e08',
    storageBucket: 'womensafety-81e08.firebasestorage.app',
    iosClientId: '890807422379-os2vl1cdo1g587gnjbu5att865uqpo7f.apps.googleusercontent.com',
    iosBundleId: 'com.example.sanrakshaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMxnwfPTudvRN8u7T50NhQtyDThgoatoI',
    appId: '1:890807422379:ios:73e74ad7271deaf986d6ee',
    messagingSenderId: '890807422379',
    projectId: 'womensafety-81e08',
    storageBucket: 'womensafety-81e08.firebasestorage.app',
    iosClientId: '890807422379-os2vl1cdo1g587gnjbu5att865uqpo7f.apps.googleusercontent.com',
    iosBundleId: 'com.example.sanrakshaa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBupiz-mn2BaiCwRsDEOwe2GMvR3PLYbbQ',
    appId: '1:890807422379:web:9efeb05a664ed50286d6ee',
    messagingSenderId: '890807422379',
    projectId: 'womensafety-81e08',
    authDomain: 'womensafety-81e08.firebaseapp.com',
    storageBucket: 'womensafety-81e08.firebasestorage.app',
    measurementId: 'G-0XRFKC3GYH',
  );
}
